export const GET_POKEMON_LIST = "GET_POKEMON_LIST";
export const SET_POKEMON_LIST = 'SET_POKEMON_LIST';

export const SET_ALL_POKEMON_LIST = 'SET_ALL_POKEMON_LIST';


export const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
export const SET_POKEMON_BY_ID = 'SET_POKEMON_BY_ID';

export const SET_POKEMON_ID = 'SET_POKEMON_ID';


export const RESET_POKEMON_DATA = "RESET_POKEMON_DATA";
export const SET_API_CALL_INPROGRESS = "API_CALL_INPROGRESS";